### ISSUE TITLE
[bug] Minor issue with table views

### ISSUE THREAD

**Issue by T145** [CallMeKass/pfSense-palenight#11] opened 2023-07-18 14:54 UTC
Specifically in pfBlockerNG, the feed alias groups listed in tables can be completely unreadable.
![screenshot](https://github.com/callmekass/pfSense-palenight/assets/1214129/321e8cd1-d894-43d6-b21d-71189577d411)

**Comment by beornlake** [comment] 2023-07-18 20:04
This is more of a pfBlockerNG problem rather than a theme issue. pfBNG has hard-coded in-line CSS that doesn’t use the theme variables, so the theme can’t override:
![Screenshot 2023-07-20-154758](https://github.com/callmekass/pfSense-palenight/assets/3237644/b6bde0b8-fe02-4e4a-aaf5-712f51adbb8f)

**Comment by tyler-holm** [comment] 2023-07-25 21:38
Closing because this is a problem with the pfBlockerNG package and not the theme. 

pfBlocker could avoid having this issues with themes by: 
1. using classes instead of inline css
2. adding a border color instead of a background color
3. using a "status" column to portray information instead of styling

**Closed as completed by tyler-holm** 2023-07-25 21:38 UTC

**Comment by tyler-holm** [comment] 2023-07-25 22:08
The pfBlockerNG file causing the problem is [HERE ](https://github.com/pfsense/FreeBSD-ports/blob/2e00b4bca4859dc1b59dd65464af90130d013609/net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_feeds.php) if anyone wants to checkout their repo and fix it.
